### ISSUE TITLE
Setup communication infrastructure for meetup  [EPIC]

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/operate-first-data-science-community#4]
We would like to start hosting regular Data Science Meet Ups as part of the operate first community. Before we promote the meetup there is some necessary communications infrastructure and planning that needs to be put in place. This issue represents the epic for all things that need to happen for us to be ready to promote the meetup. 

- [x] Create [repo](https://github.com/aicoe-aiops/cloud-first-data-science-community) to store community docs
- [x] Create issue template to suggest and track talks https://github.com/aicoe-aiops/cloud-first-data-science-community/pull/2
- [x] Create public ongoing calendar [invite](https://calendar.google.com/calendar/r?eid=X2VkcG40bGI3YnQ4NjJnYmg4b3JtdWpyODZkMDRvaHI2ZjFobW91Ymk4OTc2bW9xaDk1cGcgYWR1Z2dhbEByZWRoYXQuY29t&ctok=YWR1Z2dhbEByZWRoYXQuY29t) 
- [x] Create public [bluejeans meeting](https://bluejeans.com/8781928820)
- [x] Create [slack channel](https://operatefirst.slack.com/archives/C02KY881CJE )
- [x] Create project [board](https://github.com/orgs/aicoe-aiops/projects/28) 
- [x] Create mailing list  
- [x] Create landing page on OPF site https://github.com/operate-first/operate-first.github.io/issues/318 
- [x] Create agenda page and pre-populate for next 3 months

**Comment by MichaelClifford** [comment]
https://github.com/AICoE/okr/issues/4
